version: "3.8"

services:
    gym-tracker:
        image: mongo
        container_name: gym-tracker
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
